spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/gasAndWaters"
    username: "postgres"
    password: "733123"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yml"
    liquibase-schema: "liquibase"
    enabled: true
